# Generated by Django 6.0.4 on 2026-04-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_system', '0002_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='room_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
